const CONST = {
  REACT_APP_BASE_URL_WSS: import.meta.env.VITE_REACT_APP_BASE_URL_API_WSLINK,
  REACT_APP_BASE_URL_HTTP: import.meta.env.VITE_REACT_APP_BASE_URL_API_HTTPLINK,
  REACT_APP_BASE_KEY: import.meta.env.VITE_REACT_APP_BASE_KEY_API,
};

export default CONST;
